#!/bin/bash
#load a module
 
module="char_dev"
device="char_dev"
mode="777"
 
/sbin/insmod ./${module}.ko || exit 1
 
major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
 
mknod /dev/${module} c $major 0
chmod $mode /dev/${device}
 
devinfo=`ls -l /dev/${device}`
 
echo "insmod    :$module.ko"
echo "major :$major"
echo "devinfo   :$devinfo"
